<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="38418" started-at="2019-01-14T02:38:50Z" finished-at="2019-01-14T02:39:28Z">
    <groups>
    </groups>
    <test name="Test1" duration-ms="38418" started-at="2019-01-14T02:38:50Z" finished-at="2019-01-14T02:39:28Z">
      <class name="com.pol.zoho.testcases.LoginTest">
        <test-method status="PASS" signature="setUpFramework()[pri:0, instance:com.pol.zoho.testcases.LoginTest@3bd40a57]" name="setUpFramework" is-config="true" duration-ms="51" started-at="2019-01-14T02:38:50Z" finished-at="2019-01-14T02:38:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpFramework -->
        <test-method status="FAIL" signature="loginTest(java.util.Hashtable)[pri:0, instance:com.pol.zoho.testcases.LoginTest@3bd40a57]" name="loginTest" duration-ms="37263" started-at="2019-01-14T02:38:50Z" data-provider="masterDP" finished-at="2019-01-14T02:39:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{browser=firefox, password=vfgg, Runmode=Y, username=ddd@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[failing the login test]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: failing the login test
at org.testng.Assert.fail(Assert.java:96)
at com.pol.zoho.testcases.LoginTest.loginTest(LoginTest.java)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(java.util.Hashtable)[pri:0, instance:com.pol.zoho.testcases.LoginTest@3bd40a57]" name="loginTest" duration-ms="23303" started-at="2019-01-14T02:38:50Z" data-provider="masterDP" finished-at="2019-01-14T02:39:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{browser=chrome, password=sddd, Runmode=Y, username=a@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[failing the login test]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: failing the login test
at org.testng.Assert.fail(Assert.java:96)
at com.pol.zoho.testcases.LoginTest.loginTest(LoginTest.java)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(java.util.Hashtable)[pri:0, instance:com.pol.zoho.testcases.LoginTest@3bd40a57]" name="loginTest" duration-ms="23887" started-at="2019-01-14T02:38:50Z" data-provider="masterDP" finished-at="2019-01-14T02:39:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{browser=chrome, password=dee, Runmode=Y, username=SS@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[failing the login test]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: failing the login test
at org.testng.Assert.fail(Assert.java:96)
at com.pol.zoho.testcases.LoginTest.loginTest(LoginTest.java)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.pol.zoho.testcases.LoginTest@3bd40a57]" name="tearDown" is-config="true" duration-ms="1944" started-at="2019-01-14T02:39:14Z" finished-at="2019-01-14T02:39:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.pol.zoho.testcases.LoginTest@3bd40a57]" name="tearDown" is-config="true" duration-ms="1602" started-at="2019-01-14T02:39:15Z" finished-at="2019-01-14T02:39:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.pol.zoho.testcases.LoginTest@3bd40a57]" name="tearDown" is-config="true" duration-ms="371" started-at="2019-01-14T02:39:28Z" finished-at="2019-01-14T02:39:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.pol.zoho.testcases.LoginTest -->
    </test> <!-- Test1 -->
  </suite> <!-- Suite -->
</testng-results>
