<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="2" total="5" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Login sucessfully executed]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="D:\download.jpg">Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="D:\download.jpg"><img src="D:\download.jpg" height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="D:\download.jpg">Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="D:\download.jpg"><img src="D:\download.jpg" height=200 width=200></img></a>]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="2574" started-at="2018-08-19T04:17:17Z" finished-at="2018-08-19T04:17:19Z">
    <groups>
    </groups>
    <test name="DataDrivenFrameworkTest" duration-ms="2574" started-at="2018-08-19T04:17:17Z" finished-at="2018-08-19T04:17:19Z">
      <class name="com.ddf.testcases.BankMangerLogin">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.ddf.testcases.BankMangerLogin@5ace1ed4]" name="setUp" is-config="true" duration-ms="12280" started-at="2018-08-19T04:17:04Z" finished-at="2018-08-19T04:17:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginAsBankManager()[pri:0, instance:com.ddf.testcases.BankMangerLogin@5ace1ed4]" name="loginAsBankManager" duration-ms="1136" started-at="2018-08-19T04:17:17Z" finished-at="2018-08-19T04:17:18Z">
          <reporter-output>
            <line>
              <![CDATA[Login sucessfully executed]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.ddf.testcases.BankMangerLogin@5ace1ed4]" name="tearDown" is-config="true" duration-ms="2176" started-at="2018-08-19T04:17:19Z" finished-at="2018-08-19T04:17:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.ddf.testcases.BankMangerLogin -->
      <class name="com.ddf.testcases.AddCustomer">
        <test-method status="FAIL" signature="addCustomer(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.ddf.testcases.AddCustomer@1613674b]" name="addCustomer" duration-ms="792" started-at="2018-08-19T04:17:18Z" data-provider="getData" finished-at="2018-08-19T04:17:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ram]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[dash]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[6789.0]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[customer not added sucessfully]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: customer not added sucessfully
at org.testng.Assert.fail(Assert.java:96)
at com.ddf.testcases.AddCustomer.addCustomer(AddCustomer.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a target="_blank" href="D:\download.jpg">Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="D:\download.jpg"><img src="D:\download.jpg" height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method status="FAIL" signature="addCustomer(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.ddf.testcases.AddCustomer@1613674b]" name="addCustomer" duration-ms="540" started-at="2018-08-19T04:17:19Z" data-provider="getData" finished-at="2018-08-19T04:17:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[sam]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[df]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[44554.0]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[customer not added sucessfully]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: customer not added sucessfully
at org.testng.Assert.fail(Assert.java:96)
at com.ddf.testcases.AddCustomer.addCustomer(AddCustomer.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a target="_blank" href="D:\download.jpg">Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="D:\download.jpg"><img src="D:\download.jpg" height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomer -->
      </class> <!-- com.ddf.testcases.AddCustomer -->
    </test> <!-- DataDrivenFrameworkTest -->
  </suite> <!-- Suite -->
</testng-results>
